### ISSUE TITLE
Crashing when updating files in group.

### ISSUE THREAD

**Issue by jogvargas7** [DemonsawCommunity/demonsaw#5]
I created a group. Updated group. Tried to attach an mp3 file and update again, then the app crashes. Restarted. Tried to attach a couple of ppt files and a couple of docx files and it crashes after adding another one and updating. The documents are relatively small. The mp3 is at least 22mb. Is there a size limitation on the upload? I can try and replicate the issue but I look at the log when it crashes and all it says is APPCRASH.

**Comment by dev247** [comment]
It is easier to troubleshoot with you on demonsaw rather than comments of a issue post; but to answer your question there are no file size limitations within demonsaw, it will use as many system resources as necessary to do what you are attempting.

- What  OS is this on and what version of demonsaw are you running? (Demonsaw 3.0.2 Beta 4 is current)

- By adding files do you mean under the share tab or as a source of entropy for a group?
- If you mean under the share tab, does the user you are running demonsaw as have permissions to access the files you are attempting to share?

**Comment by jogvargas7** [comment]
Issue was user's lack of knowledge on how to work the thing. I apologize. But to point out the details as it did still crash multiple times, here they are:

1) OS was Win 8.1 running current version of DS.
2) Adding as source of entropy for a group.
3) Not under share tab. Tried it though with elevated access as I set the app to run as admin and would go through smoothly. Although on Windows 10 however, it stalled and crashed when I tried to add files under share tab. Tried to replicate the issue again but would not happen. 

Thanks. What will your name be in Demonsaw should I run into any other issues? I agree that that would be a better avenue for troubleshooting too.

**Comment by dev247** [comment]
I go by dekka on demonsaw, there are a few in demonsaw chat that can help deduce the issue.

for entropy sources, make sure you don't have too many iterations as that will lock up demonsaw if your computer can't handle generating the crypto.

This might be a bug with the last build though, we caught an issue with threads and released another build tonight.
